### ISSUE TITLE
Saved Changes Dont Apply ?

### ISSUE THREAD

**Issue by SephVII** [Invasor-de-Fronteiras/mhfrontier-cq-tool#21]
I was trying and mess around with it but for whatever reason the saved changes show up in the Editor but not in the questfile.

It says that the quest was Successfully saved after hitting the save button and when loading the same questfile back the changes are shown in the Editor for me. Checking ingame and manually via hex editing the changes arnt applied at the file.
Not sure why or how tho.

Files are Decrypted and the changes i tried i tested with manuell hex editing and everything went fine. I Also double checked if its the right file tho.

**Comment by rainapepe** [comment]
Hi Seph!

What changes have you made and tested? I'll check as soon as I can, but some values like the reward table and texts/strings like the title are saved at the end of the file, because they have dynamic sizes

**Comment by SephVII** [comment]
> 

For the purpose of testing i tried changing the Main Monster Only. i switched out Akantor for Keo. That was all

**Comment by rainapepe** [comment]
You must have only changed the quest objective, not the monster spawn

**Comment by SephVII** [comment]
> You must have only changed the quest objective, not the monster spawn

i changed both i double checked everything.

I mean i actually wanted to make sure sure so i edited also the quest String a lil the Quest Info or the String didnt apply at all either. And im not sure why tho.

**Comment by Tsugami** [comment]
Seph, can you stream your screen to us on [Discord](https://discord.gg/8U8MvdvZ)? I don't think we'll be able to move forward by text

**Comment by SephVII** [comment]
SephVII#2197

**Comment by Tsugami** [comment]
@SephVII was using an old version  :))
