### ISSUE TITLE
can't load refrontier

### ISSUE THREAD

**Issue by ezemania2** [Invasor-de-Fronteiras/mhfrontier-cq-tool#25]
![image](https://user-images.githubusercontent.com/81659486/191535944-f6ddc6ca-2ccf-47f5-b74a-9f275737f0b0.png)
Refrontier won't load and idk why
I said to me he can't found the directory

**Comment by ezemania2** [comment]
mb I wasn't enderstand how it works

**Comment by rainapepe** [comment]
Hi ezemania, we use this method to make it easier to run ReFrontier, you need to download a build of ReFrontier and put it in the ReFrontier folder inside the CQ Editor folder
